import { mitr } from "@/styles/font"
import "@/styles/globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link rel="icon" href=" "  />
      <body className={mitr.className}>{children}</body>
    </html>
  );
}
